// <auto-generated />
using System;
using GestorDeVuelosProyectoFinal.src.Shared.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestorDeVuelosProyectoFinal.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260415040741_Cities")]
    partial class Cities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("GestorDeVuelosProyectoFinal.src.Moduls.Cities.Infrastructure.Entity.CitiesEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.Property<Guid>("Regions_id")
                        .HasColumnType("char(36)")
                        .HasColumnName("regions_id");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Regions_id");

                    b.ToTable("cities", (string)null);
                });

            modelBuilder.Entity("GestorDeVuelosProyectoFinal.src.Moduls.Continents.Infrastructure.Entity.ContinentsEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Continents", (string)null);
                });

            modelBuilder.Entity("GestorDeVuelosProyectoFinal.src.Moduls.Countries.Infrastructure.Entity.CountriesEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<Guid>("Continents_id")
                        .HasColumnType("char(36)")
                        .HasColumnName("continente_id");

                    b.Property<string>("IsoCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)")
                        .HasColumnName("iso_code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Continents_id");

                    b.HasIndex("IsoCode")
                        .IsUnique();

                    b.ToTable("countries", (string)null);
                });

            modelBuilder.Entity("GestorDeVuelosProyectoFinal.src.Moduls.DocumentTypes.Infrastructure.Entity.DocumentTypesEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("document_types", (string)null);
                });

            modelBuilder.Entity("GestorDeVuelosProyectoFinal.src.Moduls.Regions.Infrastructure.Entity.RegionsEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<Guid>("Countries_id")
                        .HasColumnType("char(36)")
                        .HasColumnName("countries_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("Countries_id");

                    b.ToTable("regions", (string)null);
                });

            modelBuilder.Entity("GestorDeVuelosProyectoFinal.src.Moduls.Cities.Infrastructure.Entity.CitiesEntity", b =>
                {
                    b.HasOne("GestorDeVuelosProyectoFinal.src.Moduls.Regions.Infrastructure.Entity.RegionsEntity", "Regions")
                        .WithMany("Cities")
                        .HasForeignKey("Regions_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Regions");
                });

            modelBuilder.Entity("GestorDeVuelosProyectoFinal.src.Moduls.Countries.Infrastructure.Entity.CountriesEntity", b =>
                {
                    b.HasOne("GestorDeVuelosProyectoFinal.src.Moduls.Continents.Infrastructure.Entity.ContinentsEntity", "Continents")
                        .WithMany("Countries")
                        .HasForeignKey("Continents_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Continents");
                });

            modelBuilder.Entity("GestorDeVuelosProyectoFinal.src.Moduls.Regions.Infrastructure.Entity.RegionsEntity", b =>
                {
                    b.HasOne("GestorDeVuelosProyectoFinal.src.Moduls.Countries.Infrastructure.Entity.CountriesEntity", "Countries")
                        .WithMany("Regions")
                        .HasForeignKey("Countries_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Countries");
                });

            modelBuilder.Entity("GestorDeVuelosProyectoFinal.src.Moduls.Continents.Infrastructure.Entity.ContinentsEntity", b =>
                {
                    b.Navigation("Countries");
                });

            modelBuilder.Entity("GestorDeVuelosProyectoFinal.src.Moduls.Countries.Infrastructure.Entity.CountriesEntity", b =>
                {
                    b.Navigation("Regions");
                });

            modelBuilder.Entity("GestorDeVuelosProyectoFinal.src.Moduls.Regions.Infrastructure.Entity.RegionsEntity", b =>
                {
                    b.Navigation("Cities");
                });
#pragma warning restore 612, 618
        }
    }
}
